### ISSUE TITLE
panic: Unknown grammar

### ISSUE THREAD

**Issue by brunoamaral** [client9/csstool#1]
I'm not sure what is happening here, but trying to run this command resulted in an unexpected error.

`curl -s https://brunoamaral.eu/assets/css/main-min.css | csscut -debug -html 'public/**/*.html' > main-reduced-min.css`

```
panic: Unknown grammar

goroutine 1 [running]:
github.com/client9/csstool.(*CSSFormat).Format(0xc420147860, 0x112fc00, 0xc42000c010, 0x112fc20, 0xc42000c018, 0xc420147860, 0x0)
	/Users/brunoamaral/go/src/github.com/client9/csstool/cssformat.go:236 +0x1dfb
main.main()
	/Users/brunoamaral/go/src/github.com/client9/csstool/cmd/csscut/main.go:48 +0x38c
```

**Comment by client9** [comment]
thanks for report... the code is very new and haven't tested on a number of different CSS input sources

**Comment by client9** [comment]
@brunoamaral please try again and let know 

1. doesn't panic
2. strips the correct parts

also you can unminify using:

```bash
curl -s https://brunoamaral.eu/assets/css/main-min.css | cssformat
```

it still needs a little work, but might be useful in see what happened or not.

thanks again!

n

**Comment by brunoamaral** [comment]
Worked and cut 15KB out of the original file. I still need to find a way to test and make sure it's not cutting some necessary rules.
